# fly.toml app configuration file for toolbox-api
# See https://fly.io/docs/reference/configuration/

app = 'toolbox-api'
primary_region = 'dfw'

[build]
  dockerfile = "Dockerfile"

[env]
  # Variables de entorno se pueden definir aquí o con 'fly secrets set'
  FLY = "true"

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  # Configuración de health checks
  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

# Configuración del volumen para la base de datos SQLite
[[mounts]]
  source = "toolbox_data"
  destination = "/data"

# Configuración de la máquina virtual
[[vm]]
  size = "shared-cpu-1x"  # Ajusta según necesidades

# Configuración de logs
[metrics]
  port = 8000
  path = "/metrics"
